### ISSUE TITLE
Wording of new Reagents column is somewhat confusing

### ISSUE THREAD

**Issue by F-Lambda** [TLDRMissions/PublicOrdersReagentsColumn#10]
With the icons of needed reagents being shown in the column, "None" could be interpreted as "No additional reagents are needed", when the actual meaning is the opposite. The mixture of meanings makes it slightly headache-inducing to interpret.

With the meaning of the Reagents icons being "What do you need to provide", it might be good to provide an option to swap "None" and "All".

**Comment by teelolws** [comment]
"None" and "All" are the game defaults. If I swap them thats just going to confuse people even more. What I could do is just show all the icons instead of "None".

**Comment by F-Lambda** [comment]
I was thinking of having current be default with option to change, but showing all icons also works. Was unsure if that would be too many icons.
