### ISSUE TITLE
[Enhancement] Show red highlight for unlearned recipes on all crafting order tabs

### ISSUE THREAD

**Issue by NoShotz** [TLDRMissions/PublicOrdersReagentsColumn#12]
Would be nice if that was a thing on all the crafting order tabs as seeing at a glance what you can't craft is really useful, and it would make the look between tabs more consistent.

**Comment by teelolws** [comment]
I'll implement it as soon as I see Public Orders on my server. Few people ever list any anymore.

**Comment by NoShotz** [comment]
I've seen a bunch personally, I basically check the public orders tab every time I go to the crafting table, you'll probably find them that way too.
