### ISSUE TITLE
[Enhancement] Show a panel that sums up all reagents that are required across all patron orders

### ISSUE THREAD

**Issue by milan-stojanovic** [TLDRMissions/PublicOrdersReagentsColumn#13]
Like the title says, it would be useful for people that are purchasing reagents from AH for public/patron orders, to have a panel that shows a list of all required reagents across all patron orders. Something like this:

- 2x Carapace-Backed Hide
- 305x Gloom Chitin
- 195x Stormcharged Leather
- 1x Kaheti Swarm Chitin
- 1x Sunless Carapace

This way it is easier to note down everything that needs to be purchased. I think in general this is more useful for patron orders, rather than public orders.

Awesome addon btw!

**Comment by jcottr** [comment]
Love this idea. I'd add one refinement: only total for the orders that you can complete--the ones that aren't red. I.E. "total for all orders with known recipes."

**Comment by teelolws** [comment]
Probably not going to do this as there are other addons already that do this sort of thing! 

I haven't tried it myself, but I'd heard this one can do that? https://www.curseforge.com/wow/addons/profession-shopping-list

**Comment by milan-stojanovic** [comment]
> Probably not going to do this as there are other addons already that do this sort of thing!
> 
> I haven't tried it myself, but I'd heard this one can do that? https://www.curseforge.com/wow/addons/profession-shopping-list

Looks really good, and it should definitely speed up the process. Thanks!
