### ISSUE TITLE
[Enhancement] Show missing reagents on Personal Orders tab

### ISSUE THREAD

**Issue by jcottr** [TLDRMissions/PublicOrdersReagentsColumn#14]
I have (at least) one toon with each profession and like to have my scribe craft their treatises weekly. To do this I have them send a personal order with no mats (see screenshot below). Each one requires different reagents, so it would be helpful to show the missing reagents on the Personal Orders tab just like on the Patron tab.

<img width="1356" alt="personal-work-orders" src="https://github.com/user-attachments/assets/a60e4503-bb1e-401a-9cdd-8e6a3eb28798">

**Comment by teelolws** [comment]
Its supposed to show that already. Is it not working?

**Comment by jcottr** [comment]
> Its supposed to show that already. Is it not working?

Oh, odd. No, it's not. The screenshot in the original post is what I see.

I do see the list of missing reagents on the Public and Patron tabs. Haven't tested the Guild tab yet.

In case it's relevant I'm on retail, live version (11.0.2.56819 amd64), on macOS (Sequoia 15.0.1). I'll try recreating later today (I've already filled all the orders shown in the screenshot) and see:

1. if the problem persists when No Mats; No Make is the _only_ addon enabled
2. if I can trap any errors that might be useful

Do you have any suggestions for a debugging addon that would provide more useful details than the others?

**Comment by teelolws** [comment]
It shouldn't be listing reagents on the Public tab as they're always provided now.
