### ISSUE TITLE
Addon (TWW) Shows all recipes as "you can craft" unless you DO NOT HAVE IT - This is BAD!

### ISSUE THREAD

**Issue by Xpatro** [TLDRMissions/PublicOrdersReagentsColumn#18]
Was using This addon (NO MATS: NO MAKE) in Dragonflight and it was flawless, absolutely the best ever....
coming over to TWW, about 3 months later then release only to be absolutely annoyed... this addon is so broken its sad!

1. It only acceptes the correct color for (RED) for "Unlearned Recipes"
2. Crafts you Know, But do NOT HAVE MATERIALS for, are not shown as (Yellow) and materials i have of those - not highlighted.
3. Every Craft shows as (No-colored), when clicking some... i cant make since materials are not something i have...
4. Crafts i dont have enough (Concentration) to boost to complete/craft not warning me before clicking or opening it....

Would appricate if this could be fixed Really-really quickly please!
*[https://imgur.com/a/2uUHMpQ](IMGUR-ALBUM)
![e99a1c37d279b5eea7e8e64690ff771a](https://github.com/user-attachments/assets/7d76263f-3d74-474a-b27a-0eafa48e922e)
![d00051b3d88b3c0c1be6147517b16427](https://github.com/user-attachments/assets/7718d814-5e93-4d3c-8a5a-84f3e93cfc4e)
![f5e62ca86f41a013acdd84556519eba7](https://github.com/user-attachments/assets/1f3e1c9e-40c6-4bc2-807b-2acef4f4bf5c)

**Comment by teelolws** [comment]
Public orders have to provide materials now, so no need to highlight them. The vast majority of NPC orders do not provide materials, so highlighting 99% of them amounts to visual clutter. You can already see from the Reagents column if they require materials and what they are.

What I will do is highlight rows in the Guild, NPC, and Personal tabs that do not require reagents:
![image](https://github.com/user-attachments/assets/c33d7d25-f3da-45fe-9a55-fae8da0f2729)
