### ISSUE TITLE
Only seems to work for the top order

### ISSUE THREAD

**Issue by basdhaan** [TLDRMissions/PublicOrdersReagentsColumn#2]
all orders here dont provide mats: https://imgur.com/a/GEvJOxa

**Comment by basdhaan** [comment]
same result: https://imgur.com/a/tfN1UUs

**Comment by teelolws** [comment]
What region/server are you on? If you're on NA I'll come onto your server and check it out.

**Comment by basdhaan** [comment]
EU, tarren mill

**Comment by basdhaan** [comment]
it does hide the orders once i click on the specific items

**Comment by teelolws** [comment]
Oh well. I'll have to watch for the problem on one of my servers then.

If you click into each item, does it still at least hide the listings that don't supply mats?

**Comment by basdhaan** [comment]
the point of getting the addon was saving me that click tho. until now i was just putting people that order stuff for 1g and no mats on my ignore list, which has the same effect.

**Comment by teelolws** [comment]
There isn't much I can do without access to a server with a large list of orders like yours. Unless someone else with access is willing to step through the code and find where its breaking.

Make sure you have addon errors turned on, see if its throwing up an error:

`/console scriptErrors 1`

**Comment by basdhaan** [comment]
im not getting any errors. nothing in buggrabber.

**Comment by basdhaan** [comment]
i think i found the bug https://github.com/TLDRMissions/PublicOrdersReagentsColumn/blob/main/PublicOrdersReagentsColumn.lua#L58
it does work on my JC

**Comment by teelolws** [comment]
Yeah JC was the only profession I was able to test it on - its the only one on my server with enough orders to trigger buckets.-

**Comment by teelolws** [comment]
Good catch.

**Comment by teelolws** [comment]
Try this:
[PublicOrdersReagentsColumn.zip](https://github.com/TLDRMissions/PublicOrdersReagentsColumn/files/11076609/PublicOrdersReagentsColumn.zip)
