### ISSUE TITLE
Hide listings checkbox not working, throws LUA error

### ISSUE THREAD

**Issue by hollo6** [TLDRMissions/PublicOrdersReagentsColumn#3]
Trying to hide no-mats listings, ticking the checkbox and then clicking Search again throws the following LUA error (and all the listings remain shown):

2x ...cOrdersReagentsColumn/PublicOrdersReagentsColumn.lua:30: attempt to compare number with nil
[string "@PublicOrdersReagentsColumn/PublicOrdersReagentsColumn.lua"]:30: in function `recursion'
[string "@PublicOrdersReagentsColumn/PublicOrdersReagentsColumn.lua"]:38: in function <...cOrdersReagentsColumn/PublicOrdersReagentsColumn.lua:19>
[string "=[C]"]: ?
[string "=[C]"]: in function `ShowGeneric'
[string "@Blizzard_Professions/Blizzard_ProfessionsCrafterOrderPage.lua"]:743: in function `ShowOrders'
[string "@Blizzard_Professions/Blizzard_ProfessionsCrafterOrderPage.lua"]:756: in function `OrderRequestCallback'
[string "@Blizzard_Professions/Blizzard_ProfessionsCrafterOrderPage.lua"]:642: in function <...Professions/Blizzard_ProfessionsCrafterOrderPage.lua:642>

Locals:
collection = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
}
(for index) = 1
(for limit) = 6
(for step) = 1
i = 1
(*temporary) = 200
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to compare number with nil"
dataProvider = <table> {
 InsertTableRange = <function> defined @SharedXML/DataProvider.lua:66
 InsertInternal = <function> defined @SharedXML/DataProvider.lua:42
 collection = <table> {
 }
 ReverseEnumerate = <function> defined @SharedXML/DataProvider.lua:26
 FindElementDataByPredicate = <function> defined @SharedXML/DataProvider.lua:172
 GetSize = <function> defined @SharedXML/DataProvider.lua:34
 GenerateCallbackEvents = <function> defined @SharedXML/CallbackRegistry.lua:181
 DoesFrameHaveEvent = <function> defined @SharedXML/CallbackRegistry.lua:194
 callbackTables = <table> {
 }
 Flush = <function> defined @SharedXML/DataProvider.lua:199
 RegisterCallback = <function> defined @SharedXML/CallbackRegistry.lua:75
 RemoveByPredicate = <function> defined @SharedXML/DataProvider.lua:104
 SetUndefinedEventsAllowed = <function> defined @SharedXML/CallbackRegistry.lua:42
 UnregisterCallback = <function> defined @SharedXML/CallbackRegistry.lua:150
 RegisterCallbackWithHandle = <function> defined @SharedXML/CallbackRegistry.lua:119
 FindByPredicate = <function> defined @SharedXML/DataProvider.lua:164
 HasSortComparator = <function> defined @SharedXML/DataProvider.lua:141
 GetCallbackTables = <function> defined @SharedXML/CallbackRegistry.lua:46
 GetCallbacksByEvent = <function> defined @SharedXML/CallbackRegistry.lua:54
 SecureInsertEvent = <function> defined @SharedXML/CallbackRegistry.lua:69
 Remove = <function> defined @SharedXML/DataProvider.lua:81
 RemoveIndexRange = <function> defined @SharedXML/DataProvider.lua:115
 Enumerate = <function> defined @SharedXML/DataProvider.lua:22
 OnLoad = <function> defined @SharedXML/CallbackRegistry.lua:34
 TriggerEvent = <function> defined @SharedXML/CallbackRegistry.lua:124
 SetSortComparator = <function> defined @SharedXML/DataProvider.lua:134
 Insert = <function> defined @SharedXML/DataProvider.lua:48
 UnregisterEvents = <function> defined @SharedXML/CallbackRegistry.lua:165
 InsertTable = <function> defined @SharedXML/DataProvider.lua:62
 Init = <function> defined @SharedXML/DataProvider.lua:12
 GetCallbackTable = <function> defined @SharedXML/CallbackRegistry.lua:50
 ReverseForEach = <function> defined @SharedXML/DataProvider.lua:193
 IsEmpty = <function> defined @SharedXML/DataProvider.lua:38
 Find = <function> defined @SharedXML/DataProvider.lua:152
 HasRegistrantsForEvent = <function> defined @SharedXML/CallbackRegistry.lua:59
 RemoveIndex = <function> defined @SharedXML/DataProvider.lua:111
 Event = <table> {
 }
 ContainsByPredicate = <function> defined @SharedXML/DataProvider.lua:182
 GetCollection = <function> defined @SharedXML/DataProvider.lua:30
 FindIndex = <function> defined @SharedXML/DataProvider.lua:156
 Sort = <function> defined @SharedXML/DataProvider.lua:145
 ForEach = <function> defined @SharedXML/DataProvider.lua:187
 FindIndexByPredicate = <function> defined @SharedXML/DataProvider.lua:177
}

**Comment by teelolws** [comment]
Can you give me a screenshot of the crafting orders? It looks like there is an order that doesn't have a commission - which I didn't know was possible.

**Comment by teelolws** [comment]
Thanks, found the problem. Patch going up soon.

In the meantime, as a workaround just move the slider. Then move it back to 0 again if you want.
![image](https://user-images.githubusercontent.com/49792789/227904217-d8c53952-5414-49ee-b329-2fca11c28baa.png)
