### ISSUE TITLE
performance on big bucket lists

### ISSUE THREAD

**Issue by basdhaan** [TLDRMissions/PublicOrdersReagentsColumn#5]
hey, i noticed performance going down with big lists, so i did some digging. removing this line improves performance significantly. right now it starts over at the first bucket every time it removes an entry.
https://github.com/TLDRMissions/PublicOrdersReagentsColumn/blob/main/Source/PublicOrdersReagentsColumn.lua#L97

**Comment by teelolws** [comment]
Good catch, the iterator is supposed to stay the same, not be reset.
