### ISSUE TITLE
Mats column says None when all mats provided

### ISSUE THREAD

**Issue by aruberto** [TLDRMissions/PublicOrdersReagentsColumn#9]
When crafting table collapses into view that aggregates multiple identical orders into a single line, the `Mats?` column doesn't seem to be correct. For example the `Primal Molten Spellblade` - in first image, it says `None` for `Mats?` column value and there is only 1 order for that weapon.

![image](https://github.com/TLDRMissions/PublicOrdersReagentsColumn/assets/9933826/31d6f3fa-2c9f-4269-9afe-9aa3783fe6fa)

But then if I click on  `Primal Molten Spellblade`, the `Reagents` column for that single order shows that all mats are provided.

![image](https://github.com/TLDRMissions/PublicOrdersReagentsColumn/assets/9933826/42bb1c8c-d5c8-4d7b-8f4b-f60344f38b8b)

**Comment by teelolws** [comment]
Can you show me your button settings including the slider?
